x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile

  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_db

    AIRFLOW__CORE__PARALLELISM: 2
    AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: 2
    AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: 1

    DB_HOST: postgres

  volumes:
    - ./dags:/opt/airflow/dags
    - ./scripts:/opt/airflow/scripts

  depends_on:
    postgres:
      condition: service_healthy

services:

  postgres:
    image: postgres:13
    container_name: bigdata_postgres

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: default_db

    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./sql/00_init_databases.sh:/docker-entrypoint-initdb.d/00_init_databases.sh

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init

    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin

    command: version

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver

    command: webserver

    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler

    command: scheduler

volumes:
  postgres-db-volume: